# Generated by Django 6.0.3 on 2026-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_and_values', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
