# Generated by Django 6.0.3 on 2026-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc_tags',
            name='reg_type',
            field=models.BooleanField(default=False),
        ),
    ]
