# Generated by Django 6.0.3 on 2026-04-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_plc_tags_reg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plc_tags',
            old_name='tags_and_values',
            new_name='data',
        ),
    ]
