# Generated by Django 6.0.3 on 2026-04-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_rename_tags_and_values_plc_tags_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plc_tags',
            name='reg_type',
            field=models.IntegerField(choices=[(0, 'coil'), (1, 'holding_register')]),
        ),
    ]
